Add support dind

diff --git a/sknief/Dockerfile b/sknief/Dockerfile
--- a/sknief/Dockerfile
+++ b/sknief/Dockerfile
@@ -36,13 +36,16 @@ RUN apt-get update -y  \
     bash \
     bash-completion \
     curl \
+    ca-certificates  \
     dnsutils \
     git \
     gettext-base \
     jq \
+    iptables \
     net-tools \
     python3-pip \
     rsync \
+    supervisor \
     software-properties-common \
     tig \
     tree \
@@ -216,21 +219,6 @@ RUN curl -LO https://github.com/mikefarah/yq/releases/download/v${YQ_VERSION}/yq
     && chmod +x /usr/local/bin/yq
 
 ##############################
-# Install Docker
-##############################
-
-RUN install -m 0755 -d /etc/apt/keyrings \
-    && curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg \
-    && chmod a+r /etc/apt/keyrings/docker.gpg \
-    && echo \
-  "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
-  $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
-    tee /etc/apt/sources.list.d/docker.list > /dev/null \
-    && apt-get update -y
-
-RUN apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
-
-##############################
 # Install Neovim
 ##############################
 
@@ -241,6 +229,70 @@ RUN curl -LO https://github.com/neovim/neovim/releases/download/v${NEOVIM_VERSIO
     && tar -zxvf nvim-linux64.tar.gz -C /opt \
     && ln -s /opt/nvim-linux64/bin/nvim /usr/local/bin/vim \
     && rm -rf nvim-linux64.tar.gz
+
+##############################
+# Install Docker
+# Reference: https://github.com/cruizba/ubuntu-dind/tree/master
+##############################
+
+ENV DOCKER_CHANNEL=stable \
+    DOCKER_VERSION=24.0.7 \
+    DOCKER_COMPOSE_VERSION=v2.23.0 \
+    BUILDX_VERSION=v0.11.2 \
+    DEBUG=false
+
+# Docker and buildx installation
+RUN set -eux; \
+	\
+	arch="$(uname -m)"; \
+	case "$arch" in \
+        # amd64
+		x86_64) dockerArch='x86_64' ; buildx_arch='linux-amd64' ;; \
+    *) echo >&2 "error: unsupported architecture ($arch)"; exit 1 ;;\
+	esac; \
+	\
+	if ! wget -O docker.tgz "https://download.docker.com/linux/static/${DOCKER_CHANNEL}/${dockerArch}/docker-${DOCKER_VERSION}.tgz"; then \
+		echo >&2 "error: failed to download 'docker-${DOCKER_VERSION}' from '${DOCKER_CHANNEL}' for '${dockerArch}'"; \
+		exit 1; \
+	fi; \
+	\
+	tar --extract \
+		--file docker.tgz \
+		--strip-components 1 \
+		--directory /usr/local/bin/ \
+	; \
+	rm docker.tgz; \
+	if ! wget -O docker-buildx "https://github.com/docker/buildx/releases/download/${BUILDX_VERSION}/buildx-${BUILDX_VERSION}.${buildx_arch}"; then \
+		echo >&2 "error: failed to download 'buildx-${BUILDX_VERSION}.${buildx_arch}'"; \
+		exit 1; \
+	fi; \
+	mkdir -p /usr/local/lib/docker/cli-plugins; \
+	chmod +x docker-buildx; \
+	mv docker-buildx /usr/local/lib/docker/cli-plugins/docker-buildx; \
+	\
+	dockerd --version; \
+	docker --version; \
+	docker buildx version; \
+  \
+  test ! -d /opt/bash-utils  &&  echo 'mkdir -p /opt/bash-utils'
+
+COPY modprobe start-docker.sh entrypoint.sh /usr/local/bin/
+COPY supervisor/ /etc/supervisor/conf.d/
+COPY logger.sh /opt/bash-utils/logger.sh
+
+RUN chmod +x /usr/local/bin/start-docker.sh \
+	/usr/local/bin/entrypoint.sh \
+	/usr/local/bin/modprobe
+
+VOLUME /var/lib/docker
+
+# Docker compose installation
+RUN curl -L "https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose \
+	&& chmod +x /usr/local/bin/docker-compose && docker-compose version
+
+# Create a symlink to the docker binary in /usr/local/lib/docker/cli-plugins
+# for users which uses 'docker compose' instead of 'docker-compose'
+RUN ln -s /usr/local/bin/docker-compose /usr/local/lib/docker/cli-plugins/docker-compose
 
 ##############################
 # Create Work Directory
@@ -262,3 +314,5 @@ ENV PATH /usr/local/go/bin:${PATH}
 EXPOSE 22
 VOLUME ["/work/"]
 WORKDIR /work
+ENTRYPOINT ["entrypoint.sh"]
+CMD ["bash"]
